### ISSUE TITLE
Upgrade bind-api dependency to current version

### ISSUE THREAD

**Issue by ArneThess** [vladmihalcea/hypersistence-utils#555]
This project still uses jakarta.xml.bind-api Version 3.0.1. Since more and more projects use version 4.0.0, which contains breaking changes (like the removal of the deprecated jakarta.xml.bind.Validator interface), this leads to projects that are incredibly hard to maintain because different versions of the bind-api are required in the same project.

**Comment by vladmihalcea** [comment]
As you can see [here](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-60/pom.xml#L40), that dependency is optional.

So, you are in full control of what version you are using as no dependency will be imposed on you.

Since Hypersistence Utils uses a limited number of Jackson classes, it should work just fine with future versions.

Have you tried running it with Jackson 4.0, and it didn't work?

**Comment by ArneThess** [comment]
Ah, my bad. I misread the trace.

Thanks for the swift reply.

**Comment by vladmihalcea** [comment]
I'm glad I could help.
