### ISSUE TITLE
Add support for Hibernate 6.2

### ISSUE THREAD

**Issue by gastaldi** [vladmihalcea/hypersistence-utils#597]
Although it's still a CR, it's the default implementation in Quarkus 3 and needed for the `quarkus-hibernate-types` extension to work.

See https://github.com/quarkiverse/quarkus-hibernate-types/issues/123 

Hibernate 6.2 series: https://hibernate.org/orm/releases/6.2/

**Comment by vladmihalcea** [comment]
Indeed, I gave it a try on the `hypersistence-utils-hibernate-60` module, and it didn't even compile.

So, a new `hypersistence-utils-hibernate-62` module would be needed for Hibernate 6.2.

**Comment by vladmihalcea** [comment]
@gastaldi By the way, the project was changed from Hibernate Types to Hypersistence Utils. Hence, even if this issue is fixed, the dependencies have changed. So keep that in mind.

**Comment by gastaldi** [comment]
The following links may help with more information on what's changed: 

- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#type-system-changes
- https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc#type-system

**Comment by vladmihalcea** [comment]
@gastaldi The `hypersistence-utils-hibernate-60` already covers everything included in those links.

The `hypersistence-utils-hibernate-62` module requires both Hibernate 6.2 and a Spring 6 version that supports Hibernate 6.2. Only after those dependencies are ready will it be possible to have a `hypersistence-utils-hibernate-62` module.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by BParnikel** [comment]
Hi @vladmihalcea , first of all, thank you for all what you're doing.
I'm migrating our Kotlin services to latest version of Spring Boot and Hibernate and looks like 62 breaks Kotlin classes that extend `PostgreSQLEnumType` a bit. The issue is with `ImmutableDynamicParameterizedType`. Previously it just extended `ImmutableType<T>`, but in 62 it also implements `EnhancedUserType<T>`. As Kotlin is more strict on types, looks like it doesn't consider `equals`, `hashCode` and some other methods implemented in `ImmutableType<T>` as implementations of `EnhancedUserType<T>`'s one, so requires custom override for all your classes that extends `PostgreSQLEnumType`.
Not an issue, but just for you to be aware :)

**Comment by BParnikel** [comment]
Updated: tried to create custom class with dummy `super....(..)` so at least IDE doesnt screan, but compilation fails in fact because of 

> Inherited platform declarations clash: The following declarations have the same JVM signature (replace(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;):
    fun replace(p0: Any?, p1: Any?, p2: Any?): Enum<*>? defined in com.sentinelone.marketplace.util.hibernate.PostgreSQLEnumTypeKt
    fun replace(p0: Enum<*>?, p1: Enum<*>?, p2: Any?): Enum<*>? defined in org.bparnikel.PostgreSQLEnumTypeKt

**Comment by vladmihalcea** [comment]
@BParnikel This library is not tested with Kotlin. If it happens to work with Kotlin, then it's just by chance.
